#include <stdio.h>

int main(){
    char a;
    int x;
    printf("Oi meu amor, fiz um programinha pra você, saiba que tenho saudades");
    printf("\nAperte enter para continuar <--->");
    scanf("%c", &a);
    printf("Eu queria fazer algo especial pra você, mas eu tô sem dinheiro e o que eu planejei não deu certo :(");
    scanf("%c", &a);
    printf("\nContudo, saiba que eu sempre penso em você e sempre penso em quando vou te ver...");
    scanf("%c", &a);
    printf("\nAmor, eu te amo muito e sempre me pergunto se o que eu faço agora vai nos ajudar de alguma forma no futuro");
    scanf("%c", &a);
    printf("\nE eu prefiro acreditar que sim.");
    scanf("%c", &a);
    printf("\nDesde que eu cheguei aqui nessa cidade safada, eu sempre me pergunto como seria se eu ainda estivesse em Teixeira");
    scanf("%c", &a);
    printf("\nE a verdade é  que eu prefiro estar aqui nessa cidadezinha trabalhando com um futuro melhor do quer estar em teixeira sem poder te mimar");
    scanf("%c", &a);
    printf("\nConfesso que tem dias que são dificeis, a ideia de não te ter por perto me machuca muito, pois você é minha alma gêmea");
    scanf("%c", &a);
    printf("\nMas prometo que nós vamos passar por isso e um dia a gente vai poder comemorar juntos as conquistas de cada um, de forma presencial :p");
    scanf("%c", &a);
    printf("\nEnfim, não sei quando você vai conseguir ler tudo isso, mas espero que você tenha curtido seu dia/esteja curtindo!");
    scanf("%c", &a);
    printf("\n e pra você não se esquecer de mim, ouve essa musiquinha que é muito nois dois, amo-te...");
    scanf("%c", &a);
    printf("\nhttps://www.youtube.com/watch?v=V1bFr2SWP1I");
    scanf("%c", &a);
    printf("Caso não dê certo, procure por Somewhere over the Rainbow, o primeiro gordinho seduzente que você ver, clique kkkkkkkkkkk");
    scanf("%c", &a);
    printf("\nAgora um mini joguinho:");
    scanf("%c", &a);
    printf("\nSelecione o númeral certo para chegar a uma pequena imagem no final!\n");
    printf("Quem eu amo mais nesse mundo, 1 - Carol Lazaroto, 2 - Carol perfeita ou 3 - Carol Amor da minha vida?");
    scanf("%d", &x);
    printf("\n Exatamente gatinha, você...");
    scanf("%c", &a);
    printf("\nxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx");
    printf("\nxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx");
    printf("\nxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx");
    printf("\nxxxxxxxxxxxxxxx****************xxxxxxxxxxxxxxxxxxx****************xxxxxxxxxxxxxx");
    printf("\nxxxxxxxxxxx***********************xxxxxxxxxxxxx***********************xxxxxxxxxx");
    printf("\nxxxxxxxx*****************************xxxxxxx*****************************xxxxxxx");
    printf("\nxxxxxxx*******************************xxxx********************************xxxxxx");
    printf("\nxxxxx***********************************x**********************************xxxxx");
    printf("\nxxxxx***********************************************************************xxxx");
    printf("\nxxxx*************************************************************************xxx");
    printf("\nxxxx*************************************************************************xxx");
    printf("\nxxxxx***********************************************************************xxxx");
    printf("\nxxxxx***********************************************************************xxxx");
    printf("\nxxxxxx*********************************************************************xxxxx");
    printf("\nxxxxxxx*******************************************************************xxxxxx");
    printf("\nxxxxxxxx*****************************************************************xxxxxxx");
    printf("\nxxxxxxxxxx*************************************************************xxxxxxxxx");
    printf("\nxxxxxxxxxxxx*********************************************************xxxxxxxxxxx");
    printf("\nxxxxxxxxxxxxxx****************************************************xxxxxxxxxxxxxx");
    printf("\nxxxxxxxxxxxxxxxxx***********************************************xxxxxxxxxxxxxxxx");
    printf("\nxxxxxxxxxxxxxxxxxxx******************************************xxxxxxxxxxxxxxxxxxx");
    printf("\nxxxxxxxxxxxxxxxxxxxxxx************************************xxxxxxxxxxxxxxxxxxxxxx");
    printf("\nxxxxxxxxxxxxxxxxxxxxxxxxx*******************************xxxxxxxxxxxxxxxxxxxxxxxx");
    printf("\nxxxxxxxxxxxxxxxxxxxxxxxxxxxx*************************xxxxxxxxxxxxxxxxxxxxxxxxxxx");
    printf("\nxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx********************xxxxxxxxxxxxxxxxxxxxxxxxxxxxxx");
    printf("\nxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx***************xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx");
    printf("\nxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx**********xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx");
    printf("\nxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx******xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx");
    printf("\nxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx**xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx");
    printf("\nxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx");
    printf("\nxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx");
    printf("\nxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx");

    return 0;
}